export const SITE = {
  website: "https://ashrithm.com/",
  author: "Ashrith M Yerrapragada",
  profile: "https://ashrithm.com/",
  desc: "ashrith's blog",
  title: "ashrithm",
  ogImage: "astropaper-og.jpg",
  lightAndDarkMode: true,
  postPerIndex: 4,
  postPerPage: 3,
  scheduledPostMargin: 15 * 60 * 1000,
  showArchives: false,
  showBackButton: true,
  editPost: {
    enabled: false,
    text: "Edit page",
    url: "https://github.com/ashrithm/ashrithm/edit/main/",
  },
  dynamicOgImage: true,
  dir: "ltr",
  lang: "en",
  timezone: "America/New_York",
} as const;
